project:
  type: website
  output-dir: docs
  

website:
  title: "Rafe Chang"
  navbar:
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/rafechang/
      - icon: github
        href: https://github.com/rafecchang
    left:
      - href: index.qmd
        text: Home
      - href: pages/about.qmd
        text: who am I 
      - href: pages/projects.qmd 
        text: what I've done

format:
  html:
    theme: Lux
    css: styles.css
    toc: true



