project:
  type: website
  output-dir: docs
  

website:
  title: "rafecchang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - herf: about.qmd
        text: who am I 
      - herf: projects.qmd 
        text: what I've done

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



