## Summary 
Data scientist with a global perspective, skilled in applying advanced machine learning, statistical modeling, and geospatial analysis to drive sustainable energy solutions. Experienced in analyzing electric vehicle and lithium-ion battery markets, solar energy feasibility, and energy efficiency dashboards. Passionate about using data to support energy innovations and climate-positive actions.

## Professional Experience 
**Data Scientist (Capstone)** *@ Pacific Salmon Foundation*

To support biologists in modeling salmon survival, I developed predictions for outmigration timing, enabling efficient resource allocation for tagging fish in rivers. My contributions included:

- Wrote complex SQL queries to retrieve data from a relational database with 15 interconnected tables 
- Conducted exploratory data analysis for data cleaning and preprocessing with pandas
- Experimented with multiple modeling approaches, including SARIMAX, linear regression, and logistic regression, before selecting and developing a final XGBoost model 



**Branding Strategy& Business Analytics Extern** *@ Beats by Dr. Dre* 

To evaluate the effectiveness of its advertisement among Gen Z audiences, I designed and conducted a comprehensive marketing research project. My contribution include: 

- Designed research framework based on conversion funnel; successfully sampling 5.57% of the target population to gather primary data  
- Analyzed result with hypothesis testing (chi-square analysis) and perceptual mapping (dimensionality reduction) 


**Student Consultant** *@ Union Pacific Railroad* 

In response to trends in deforestation, renewable diesel, and domestic electric vehicle production, I identified potential customers and developed logistic plans accordingly. My contribution include: 

- Analyzed the U.S. electrical vehicles market and fit linear modeling to extend on existing prediction 
- Researched materials of various Lithium-Ion battery models; projected mineral demand by combining findings from electrical vehicle market analysis
- Developed logistic plans and estimated potential revenue after identifying the site locations along the battery production chain 


**Marketing Specialist** *@ Nebraska College Rodeo Program* 

In the months leading up to the annual rodeo, the program sought ways to increase attendance; I boosted team members’ online presence. My contribution included:  

- Developed webpage using HTML and CSS
- Shoot, edited and posted content on Instagram; analyzed performance metrics to optimize engagement


## Education 
**Master of Data Science** *@ University of British Columbia-Vancouver*

- •Relavent Courses: Supervised and Unsupervised Learning (sklearn, PyTorch), Spatial and Temporal Modeling (geopandas, statsmodels), Data Visualization (matplotlib, Vega-Altair), Database (PostgreSQL), Software Development, Cloud Computing, Bayesian and Frequentist Inference (r), Experimentation and Causal Inference

**Bachelor of Science in Business Administration (Honors)** *@ University of Nebraska-Lincoln* 
**Bachelor of Science in Politics, Psychology, Law, and Economics (Erasmus)** *@ University of Amsterdam* 