I create data products and content to deliver insights on energy and the environment.

## Coding Projects 

### climateDebunkers
- **Description**: A lightweight language model classifying quotes into eight different categories.
- **Tools Used**: NLPAug, DistilBERT, Optuna
- **GitHub Repo**: [CimateDebunk](https://github.com/hbandukw/ClimateDebunk)

### pvpmSimulator
- **Description**: A web app providing real-time and customizable simulation that calculates the solar energy potential loss caused by PM2.5.
- **Tools Used**: Streamlit, pvlib-python, AirNow.gov API 
- **Web App**: [pvpmSimulator](https://pvpmsimulator.streamlit.app/) (use Chrome)

### salmonSavers
- **Description**: A pipeline predicting salmon outmigration timing to optimize fieldwork timing for salmon survival analysis. 
- **Tools Used**: PL/Python, PL/SQL, XGBoost
- **GitHub Repo**: [Bottlenecks to Survival](https://github.com/brahmwg/Bottlenecks_MDS_Capstone)

### solarSavers
- **Description**: A dashboard assisting Canadian homeowners to choose the optimal panel by calculating energy and financial savings at a given location. 
- **Tools Used**: GeoPy, GeoPandas, Dash
- **GitHub Repo**: [Solar Savers](https://github.com/UBC-MDS/DSCI-532_2024_9_solar-savers)
- **Dashboard**: [Solar Savers](https://dsci-532-2024-9-solar-savers.onrender.com/)

## Writing Projects 


### Energy in the News 
- **Description**: A series of energy news written for the UBC student community. 
- **Latest Story**: [Transitioning Power: The Tariff Hike Continues](https://www.studentenergyubc.com/post/transitioning-power-the-tariff-hike-continues)
- **Full List**: [Student Energy UBC](https://www.studentenergyubc.com/blog/categories/energy-in-the-news) 
